### ISSUE TITLE
Auth problems using 'terminus remote:wp'

### ISSUE THREAD

**Issue by jedlin-bf** [pantheon-systems/docker-build-tools-ci#110]
I'm using the following test setup in Bitbucket pipelines running this image:

```yml
image: quay.io/pantheon-public/build-tools-ci:8.x-php8.1

pipelines:
  custom:
    list-sites:
      - step:
          name: List Sites
          script:
            - terminus auth:login --machine-token=$TERMINUS_MACHINE_TOKEN
            - terminus site:list
    list-users:
      - step:
          name: List Users
          script:
            - terminus auth:login --machine-token=$TERMINUS_MACHINE_TOKEN
            - terminus remote:wp gd-22.live -- user list
```

Everything seems to work just fine when I run a simple command like ```terminus site:list``` but anything that uses ```terminus remote:wp``` throws errors like this:

```bash
+ terminus remote:wp gd-22.live -- user list
Warning: Permanently added '[appserver.live.redacted-id.drush.in]:2222' (RSA) to the list of known hosts.
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
live.redacted-id@appserver.live.redacted-id.drush.in: Permission denied (password,publickey).
 [notice] Command: gd-22.live -- wp user list [Exit: 255]
 [error] 
```

I'm trying to run some scripts via Bitbucket Pipelines to do some reporting on my inventory of sites.  These are just some simplified examples to show what I'm running into.
