### ISSUE TITLE
switching from 7.4.x to 8.x-php8.1 causes permission denied errors in circleci

### ISSUE THREAD

**Issue by eriksays** [pantheon-systems/docker-build-tools-ci#115]
as the title mentions, switched from:
```
# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/build-tools-ci:7.4.x
```

to
```
defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/build-tools-ci:8.x-php8.1
```
with a working directory as: working_directory: /var/www/html/my_codebase

I now get an error in my circleCI build at the 
```
Using SSH Config Dir '/home/tester/.ssh'
git version 2.42.0
Cloning git repository
mkdir: cannot create directory ‘/var/www’: Permission denied

exit status 1
```
at the configure_env_vars > Checkout Code step.

Any thoughts on this one are appreciated.
