### ISSUE TITLE
Add google-chrome, selenium, and chromedriver

### ISSUE THREAD

**Issue by dearmond** [pantheon-systems/docker-build-tools-ci#2]
Otherwise behat `@javascript` won't run.

**Comment by jraviotta** [comment]
Try adding these services to your docker-compose.yml
```
  selenium-hub:
    image: selenium/hub
    container_name: "${PROJECT_NAME}_selenium_hub"
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    container_name: "${PROJECT_NAME}_chrome"
    ports:
    - "5900:5900"
    links:
      - selenium-hub:hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
        HUB_PORT_4444_TCP_ADDR: selenium-hub
        HUB_PORT_4444_TCP_PORT: 4444
```
