### ISSUE TITLE
Need usage documentation

### ISSUE THREAD

**Issue by jraviotta** [pantheon-systems/docker-build-tools-ci#3]
I would like to add this image to my local dev environment. It would be helpful if the README included usage examples. 

I use the docker4drupal docker-compose.yml template and have included the following:
```
  terminus:
    image: quay.io/pantheon-public/build-tools-ci
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
```
This builds the container, but I can't seem to call terminus from the php container. I would appreciate a nudge in the right direction. Thanks
